stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    - data/raw/water_potability.csv
    params:
    - data_collection.test_size
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    params:
    - model_building.n_estimators
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    outs:
    - models/model.pkl
  model_eval:
    cmd: python src/model/model_eval.py
    deps:
    - models/model.pkl
    - src/model/model_eval.py
    metrics:
    - reports/metrics.json
